server:
  port: 8000
  servlet:
    context-path: /saveME
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saveme?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql:true --> 콘솔창에 쿼리 띄우는 구문
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false